# version: '3'

# # profile_path must be define in env_file

# services:
#   soe-asynfed-client:
#     container_name: soe-asynfed-client
#     build: .
#     command: python3 /app/training_process/cifar_dataset/client/resnet18_5_chunks/docker/run_client_v2.py
#     env_file:
#       - .env
#     # these env variable can be defined in either .env file or as below
#     environment:
#       - queue_url=amqp://guest:guest@13.214.37.45:5672/%2F
#       # - queue_url=amqp://guest:guest@ 195.148.22.62:5672/%2F
#     volumes: 
#       - .:/app
#       - ${profile_path}:/app/training_process/mnist_dataset/client/profile.json



