version: '3'

#services:
#  rabbitmq:
#    image: rabbitmq:3.11-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest

services:
  fed-async-client:
    container_name: fed-async-client-soe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
    environment:
      access_key:
      secret_key:
