version: '3'

services:
  fed-async-client:
    container_name: soe-asynfed-client-1
    image: vtn13042000/asynfed_tensorflow_client:2.0.0
    environment:
      - queue_url=amqp://guest:guest@13.214.37.45:5672/%2F
      - training_exchange=test-client-tensorflow-mnist
      - local_model_folder=./weights/local_weights/
      - global_model_folder=./weights/global_weights/
      - log_path=./logs/
      - x_train_path=./data/mnist_data/train-images-idx3-ubyte.gz
      - y_train_path=./data/mnist_data/train-labels-idx1-ubyte.gz
      - x_test_path=./data/mnist_data/t10k-images-idx3-ubyte.gz
      - y_test_path=./data/mnist_data/t10k-labels-idx1-ubyte.gz
      - sleeping_time=2
      - batch_size=128
      - data_size=60000
      - tracking_point=5000


